src/es6-timed-map.ts
tests/es6-timed-map.spec.ts

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:
Added an onExpire method that gets called whenever an item from the map expires. Also added respective tests.
#29 

Added onExpire method

---

src/es6-timed-map.ts
tests/es6-timed-map.spec.ts

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:
Added a touch method that resets or sets the timer
#30, #18 

Added touch method

---

.eslintrc.js
.gitignore
package-lock.json
package.json

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain: Updated tooling.
- Integrate Prettier with ESLint (display Prettier issues as ESLint errors and have ESLint fix them)
- Remove `npx` from scripts since those packages are already installed as part of dev dependencies
- Remove `pretty-quick` since ESLint now also fixes Prettier issues
Resolves https://github.com/bradtaniguchi/es6-timed-map/issues/37

Integrate Prettier with ESLint and other small cleanups

---

src/es6-timed-map.ts
tests/es6-timed-map.spec.ts

[ ] Documentation update
[X] Bug fix
[ ] New feature
[X] Other, please explain: More tests
- Fixed but with `size` not updating
- Add test cases for `size` property
Closes #20
I'm the reviewer :P

Update size property testing

---

.dependabot/config.yml

**Purpose of this pull request**
✔️ New feature
Added depandabot config file
#31 
Added initial file would like to receive suggestions for further updates

Added Depandabot config file

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
cc-metadata.yml

Added a `cc-metadata.yml` file, adds a pull request template file, links to the Developer Certificate of Origin in the template and the contributing guidelines.
Related to #34 

Add metadata and PR template

---

tests/es6-timed-map.spec.ts

* Added tests for `get` method
* Changed Map types to any,any to allow for symbol/object keys
Closes #22 

Update get property testing

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/chore_request.md
.github/ISSUE_TEMPLATE/documentation_request.md
.github/ISSUE_TEMPLATE/feature_request.md

- Add issue templates
Closes #5 

Add issue templates

---

src/es6-timed-map.ts
tests/es6-timed-map.spec.ts
tsconfig.json

Added a Symbol.iterator method that allows iteration through for..of loops and spread syntax.
In order to check whether for..of loops work in the tests, I have enabled the downlevelIteration option in tsconfig.json.
The alternatives are switching the target to ES6 or testing the iterability through generators, which would result in less code clarity.

Add Symbol.iterator support

---

src/es6-timed-map.ts
tests/es6-timed-map.spec.ts

Added `timers` method and corresponding tests
#19 
Wasn't sure what the return type should be, open to suggestions.

Added timers method and tests

---

tests/es6-timed-map.spec.ts

Closes #23
- Added more tests
#23 

Finalize has method tests

---

src/index.ts
tests/es6-timed-map.spec.ts

Closes #21
Add more tests for the `clear` method.
#21

Add clear method tests

---

CONTRIBUTING.md
sandbox/README.md
sandbox/nodejs/.eslintrc.js
sandbox/nodejs/package.json
sandbox/nodejs/sandbox.js

- Update docs and add sandbox testing environment
Closes #48

Add nodejs sandbox example

---

tests/es6-timed-map.spec.ts

Add set tests

---

tests/es6-timed-map.spec.ts

- Add tests for keys, added more than what was there first.
Closes #25

Add keys tests

---

src/index.ts
tests/es6-timed-map.spec.ts

Add entries-test

---

tests/es6-timed-map.spec.ts

Add values tests

---

.devcontainer/devcontainer.json
.gitignore
.vscode/extensions.json

Add devcontainer and vscode default settings

---

.devcontainer/devcontainer.json
.gitignore
CONTRIBUTING.md
package-lock.json
package.json
typedoc.json

- the actual contents of typedocs seems really off though?  Will look back into this later.
**Issues closed by this pull request**
Closes #10

Add typedoc generation and docs

---

.gitignore
package-lock.json
package.json
sandbox/README.md
sandbox/nodejs/.gitignore
sandbox/ts-nodejs/.gitignore
sandbox/ts-nodejs/package.json
sandbox/ts-nodejs/sandbox.ts
sandbox/ts-nodejs/tsconfig.json
src/index.ts
tsconfig.json

- update core file with key changes
- add ts-nodejs sandbox

Add ts based sandbox, fix build issues

---

src/index.ts

- this is a breaking change, but then I'm not sure if the original
version actually worked.

Update constructor args

---

src/index.ts
tests/es6-timed-map.spec.ts

- Add more extensive testing for constructor args
- Fix issue with constructor arg types forcing callbacks.
**Issues closed by this pull request**
Closes #373

Add tests for constructor entities

---

src/index.ts
tests/es6-timed-map.spec.ts

feat: add set data validation

---

src/index.ts
tests/es6-timed-map.spec.ts

- add new alt set method
**Issues closed by this pull request**
Closes #382

Add new alt-set method
